# Add documentation label to any change in documentation related files
documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        "docs/**/*", # All files, including subfolders
        "README.md",
        "**/README.md",
        "CONTRIBUTING.md",
      ]

maintenance:
- any:
  - changed-files:
    - any-glob-to-any-file: [
        ".vscode/**/*", # All files, including subfolders
        ".github/**/*", # All files, including subfolders
        ".reuse/*",
        "LICENSES/*",
        ".editorconfig",
        "**/.gitignore",
        "build.py",
      ]
